# Generated by Django 4.2.4 on 2023-09-12 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'permissions': (('can_mark_store', 'Set store as noticed'),)},
        ),
    ]
